src/v0.10/providers.json
Fixes #6 
Two commits:
- The first adds the `homepage` property for all providers, setting it to `null`.
- The second updates this property for the providers: `aiida`, `exmpl`, `mcloud`, `optimade`.
=> Add homepage to providers.json

v0.10/info/index.html
In the process of testing the validator from the python tools package as a GH action (that could be added to this repository), I've discovered that the current response at https://www.optimade.org/providers/info does not validate as JSON, due to some trailing commas. This PR fixes that.
=> Remove commas from /info JSON

v0.10/info/index.html
`available_api_versions` should be a list of dicts, not a single dict. This PR fixes that (needs to be merged before #11).
=> Fixes to available_api_versions

.github/workflows/validate.yml, .gitignore, tests/test_providers.py
Closes #5 (hopefully). This PR checks all commits with the optimade-python-tools validator. NB: this validates the _URL_ https://optimade.org/providers and *not* the files in this repository. It wouldn't be too much extra work to write a little python script that uses the same validator tools on this repository directly.
One open question is whether it should be only run on push, or run every day (or some other period) to ensure that the server/domain is up.
Relevant lines of config:
https://github.com/Materials-Consortia/providers/blob/580ebec395bb9a060fb65130abcc37dfd5972a51/.github/workflows/validate.yml#L5-L6
Currently the validator will fail until #10 is merged. The error message at the moment is quite opaque as it is failing at such a fundamental level (unable to parse response from …
=> Added GH action validator from optimade-python-tools

README.md, src/info/v1/index.html, src/links/v1/index.html
We need to host the providers index meta-database differently from the OPTiMaDe main website to address Materials-Consortia/OPTiMaDe#236.
Hence, we now have a dedicated subdomain for hosting the providers list via Netlify: https://providers.optimade.org
This PR changes the README.txt to update this and make a few other minor adjustments to README.md based on comments in #14 that were not addressed there.
=> Change URLs to reflect new subdomain

README.md
Fixes #17 
Apparently, for some reason, the markdown workflow that rendered README.md via netifly does not render raw URLs in markdown as links. This reverts the changes that removed the explicit markdown links.
This reverts commit cf168145727ba37e4a8d9368da6f0a283e741e82.
Preview is available at: https://deploy-preview-16--optimade-providers.netlify.com/
Compare with https://providers.optimade.org/
=> Fix URL links in README.md

src/links/v1/providers.json
Remove superfluous "title" segment of `description`, since the title is indeed already there, in form of the `name` property.
=> Update descriptions for `aiida` and `mcloud`

README.md, providers.json, src/index-metadbs/README.md, src/index-metadbs/cod/v1/info.json, src/index-metadbs/exmpl/v1/info.json, src/index-metadbs/tcod/v1/info.json, src/index-metadbs/tcod/v1/links.json, src/info/v1/info.json, src/links/v1/providers.json, tests/test_providers.py
Update `tcod` index meta-database:
- Use `tcod` ID instead of `cod`
Clarify details in README.
Re-add repo top-level symlink to `providers.json`.
Since this is referenced in READMEs, it would be good to have the file existing.
Note, this PR originally sprang from the idea of adding `meta` in the response, however, I found that this is indeed not necessary from the spec ("at least one of the top-level fields has to be present, `data` being one of them", so it's all good).
However, there were still some minor changes that could be done that I found, so the PR exists :)
=> Update to 1.0.0-rc.2

src/index-metadbs/cod/v1/info.json, src/index-metadbs/cod/v1/links.json, src/index-metadbs/exmpl/v1/info.json, src/index-metadbs/exmpl/v1/links.json, src/index-metadbs/tcod/v1/info.json, src/index-metadbs/tcod/v1/links.json, src/info/v1/info.json, src/links/v1/providers.json
Note: this makes a schema reference to https://schemas.optimade.org/openapi/v1/optimade_index.html in the schemas repo. So we probably shouldn't merge this until that subdomain has been created.
Oh, and it won't validate until the validator is updated for OPTIMADE v1.0.0
Edit (Casper): The schema reference is https://schemas.optimade.org/openapi/v1.0/optimade_index.json and it's up, good to go :)
Also, closes #41.
=> Update providers database to OPTIMADE v1.0.0 format

src/links/v1/providers.json
We moved around some of our web-pages and the optimade APIs location has changed.
=> Update providers.json with new nomad url.

README.md
This PR simply adds a link to https://www.optimade.org/providers-dashboard/.
=> Added link to providers-dashboard

README.md
This PR adds a segment of text to README.md that explains how one can easily fork this repository to host one's own index meta-database that fulfills the requirements to be added to OPTiMaDe's central list of providers.
A preview is visible at: https://deploy-preview-18--optimade-providers.netlify.com/
=> Add README.md text to help others host index meta-databases

README.md, src/index-metadbs/README.md
Closes #38.
Use `v1.0.0` instead of `develop`.
Use un-numbered link anchors.
Use the new repository name `OPTIMADE` instead of `OPTiMaDe`.
=> Update links to the online specification

src/index-metadbs/oqmd/v1/info.json, src/index-metadbs/oqmd/v1/links.json, src/links/v1/providers.json
OPTiMaDe v1.0.0 is now fully incorporated into `qmpy` (Django-based Python API that OQMD is based on). 
I can pull the new scripts onto the public `oqmd.org` website once the internal review of `qmpy` is finished, but the final base-URLs are now designated.
I will update it here when the `optimade-validator` can access `oqmd.org/optimade` for validation. Created this PR now to initiate the process.
=> Adding OQMD's info to providers.json

src/links/v1/providers.json
Now httk has support for hosting OPTIMADE v1.0.0, which we are setting up for hosting omdb. This PR updates the omdb info accordingly to point to our index meta-database.
=> Update information for omdb in providers.json

src/index-metadbs/aflow/v1/info.json, src/index-metadbs/aflow/v1/links.json, src/links/v1/providers.json
Adds the directory providers/src/index-metadbs/aflow with info.json and links.json files. Also modifies the providers.json file in accordance with the instructions in the README.
=> Add AFLOW to providers lists

src/index-metadbs/matcloud/v1/links.json, src/links/v1/providers.json
Fixes #64.
The `name` value should be a title.
I removed the first part of the `description` value to not be redundant.
=> Fix name values for matcloud

src/index-metadbs/mpds/v1/info.json, src/index-metadbs/mpds/v1/links.json, src/links/v1/providers.json
This is to introduce the Optimade support for the MPDS.
All our data of all the types are visible.
The known limitations include:
- many omitted fields in the data due to the copyright reasons
- incomplete filtering language support (_e.g._ we miss `ANY`, please, run successive requests one by one)
- still a lot of the remnants and links to the [old MPDS API](https://mpds.io/developer)
=> Add MPDS provider

.github/workflows/python_validate.yml, tests/test_providers.py
Closes #67 by no longer accumulating 404 errors on remote index meta-databases. Also disables the temporary v0 workarounds that were left in the CI.
=> Do not raise error if particular index meta-database is down

src/links/v1/providers.json
This PR adds a provider for the WIP NecrOPTIMADE service, currently hosted on Heroku.
The index meta-database is dynamic and currently only contains a single implementation if it has been requested at the `extensions/spawn` endpoint since the last deployment. Some more notes can be found at [ml-evs/necroptimade](https://github.com/ml-evs/necroptimade).
=> Add NecrOPTIMADE provider

src/index-metadbs/jarvis/v1/info.json, src/index-metadbs/jarvis/v1/links.json, src/links/v1/providers.json
This PR adds a static index meta-db for JARVIS and links out to the JARVIS-DFT database, which is now publicly available via OPTIMADE.
@knc6: I took the description from your website at https://www.nist.gov/programs-projects/jarvis-dft, please let me know if you want it to say something different.
=> Add details and static index meta-db for JARVIS

_redirects, src/landing_page.html
This PR is a potential solution for #76, by redirecting the static base URLs served here to a semi-informative landing page, rather than 404'ing.
Unfortunately netlify can't do redirects based on `Accept` headers, so serving a JSON response is not possible (unless we get rid of this HTML response). The HTML response mimics the way most providers are handling their base URLs, so I don't think there is an issue here.
=> Redirect static base URLs to a helpful landing page

src/index-metadbs/jarvis/v1/links.json
Pinging @knc6, I think this is a good idea as it will stop the multi-provider OPTIMADE clients from downloading all of JARVIS every time they query with a filter.
=> Switch off aggregation for JARVIS until filtering/pagination are implemented

tests/test_providers.py
My index meta-database is currently down due to a forced migration. This should not cause the tests here to fail.
We are currently catching `urllib.errors.HTTPError`, yet a timeout on a down database actually raises a `urllib.errors.URLError` (which `HTTPError` inherits from).
This PR simply catches `URLError` instead
=> Error handling for index meta-databases that are down

.github/workflows/python_validate.yml
As we are dropping support for python 3.7 in the optimade python tools, I think we should drop it here too.
=> Use Python 3.10 in CI and bump GH actions

src/links/v1/providers.json
This PR simply sets the necroptimade base URL to null, as I have not had time to redeploy it away from heroku (and may never).
=> Remove necroptimade base URL

src/index-metadbs/cmr/v1/info.json, src/index-metadbs/cmr/v1/links.json, src/links/v1/providers.json
Adds CMR as a provider to the ASE databases in the CMR-project (https://cmr.fysik.dtu.dk/) using the ase-optimade software: https://gitlab.com/jensj/ase-optimade
=> Add CMR provider

src/index-metadbs/mpdd/v1/info.json, src/index-metadbs/mpdd/v1/links.json, src/links/v1/providers.json
This PR adds Material-Property-Descriptor Database (MPDD) ([description](https://phaseslab.com/mpdd) / [partial access](mpdd.phaseslab.com)) and its OPTIMADE endpoint available at [mpddoptimade.phaseslab.org](http://mpddoptimade.phaseslab.org) to the list of providers. 
MPDD is a data infrastructure with around 4 million atomic structures, optimized for the high-throughput deployment of material featurizers and ML models utilizing them. While the infrastructure access is available to collaborators only, all structures in the database are made publicly available in a synchronized mirror with the data cast into the OPTIMADE-compliant schema.
The database is maintained by Prof. Zi-Kui Liu's @PhasesResearchLab ([phaseslab.org](https://phaseslab.org)) at The Pennsylvania State University.
=> Add MPDD provider

.github/workflows/ci_validate.yml, README.md, src/index-metadbs/README.md, src/index-metadbs/aflow/v1/links.json, src/index-metadbs/ccpnc/v1/info.json, src/index-metadbs/cmr/v1/info.json, src/index-metadbs/cod/v1/info.json, src/index-metadbs/exmpl/v1/info.json, src/index-metadbs/jarvis/v1/info.json, src/index-metadbs/mp/v1/info.json, src/index-metadbs/mpdd/v1/info.json, src/index-metadbs/oqmd/v1/info.json, src/index-metadbs/oqmd/v1/links.json, src/index-metadbs/tcod/v1/info.json, src/index-metadbs/twodmatpedia/v1/info.json, src/links/v1/providers.json
This PR converts many links to https (and leaves those without certificates), especially our own internal provider links.
=> Tidying up old links

src/index-metadbs/jarvis/v1/links.json
Undoes #79 and enables query aggregation on JARVIS again. Need to verify first with @knc6 that filters and pagination are working again.
=> Re-enable aggregation on JARVIS

src/index-metadbs/alexandria/v1/links.json
Now `alexandria` is being hosted by its real group (@hyllio), we can update the link here.
=> Update link for Alexandria

src/links/v1/providers.json
Hi, we updated the mcloud provider's base_url to follow a similar pattern as the mcloudarchive provider. However, we will keep a redirect from the old base_url as well.
=> update mcloud base_url

src/links/v1/providers.json
NecrOPTIMADE is dead, long live NecrOPTIMADE, this PR replaces its unused namespace with the hot new optimade-maker, which is powering the Materials Cloud Archive's OPTIMADE integration (and potentially other local projects). This prefix will be used by default when ingesting archived data locally (so may appear in static JSONL files) so I think it makes sense to register it here.
=> Rename necroptimade to optimake and update link

src/index-metadbs/matterverse/v1/info.json, src/index-metadbs/matterverse/v1/links.json, src/links/v1/providers.json
The base URL is not yet activated. 
It will be linked to: https://optimade-matterverse-ai-43429a548b75.herokuapp.com/.
=> Add matterverse provider
